declare type IconName =
  | "search"
  | "more"
  | "move"
  | "mail"
  | "briefcase"
  | "round-arrow"
  | "contact-card"
  | "uploadfile"
  | "star"
  | "eye"
  | "location"
  | "uploadfile-success"
  | "graduate"
  | "wechat"
  | "github"
  | "arrow";
